### PR TITLE
Update JUMP docs, remove SoBi

### PR DESCRIPTION
**Pull request by dschep**
SoBi recently added authentication to one of their APIs, but
added open data APIs for JUMP. Update docs for the useable APIs

### CODE REVIEW

**Comment by dschep** [comment]
Also, they recently rebranded as JUMP: https://medium.com/@jumpbikes/were-now-jump-bikes-91378342bc82

**Comment by PierrickP** [comment]
Hey, thank you for your PR.
So Jump is the new name ? and they provide system for all previous cities ?

I'm a bit surprised by datas, if you want free bikes in SF -> https://sf.jumpmobility.com/opendata/free_bike_status.json , one. Just One ?

**Comment by dschep** [comment]
The company changed names from SoBi to JUMP. JUMP is their own privately run dockless e-bike in DC & SF (yeah, I think they've barely out in SF, thus the just 1 bike @PierrickP, There were definitely days in DC towards the beginning where you'd find 0,1,2or3 bikes free). SoBi is still the brand the company (JUMP now) uses for it's existing partership-based bikeshare programs.

I'll update the docs. The SoBi docs aren't quite as useful as they were before because they've added authentication, but I think it should be open enough to use, but the docs aren't very clear, leaving all of the oauth2(iirc) details up to you.

**Comment by PierrickP** [comment]
awesome !

**Comment by ubahnverleih** [comment]
Thank you all for your support :)

**Comment by dschep** [comment]
Happy to help! Your docs have been invaluable in figuring out how to track all these new dockless bikes!

**Pull request merged**
