### PR TITLE
Update Jump

### PR DESCRIPTION
**Pull request by adur1990**
Jump was more or less completely outdated.

Unfortunately, since Jump belongs to Uber, it was really hard to find the current version of the API.
Due to some mitigations like certificate pinning and me not being a security expert at all, it required some time and both Android app and protocol reverse engineering foo to accomplish this.
To make life (hopefully) easier in the future, I also included a guide on how to reverse engineer the app and extract the required information from both the app and the HTTP traffic.

### CODE REVIEW

**Comment by adur1990** [comment]
Hi,

good question. I tried and failed.

So, Jump uses [OkHTTP3](https://square.github.io/okhttp/) for their HTTPS related stuff including certificate pinning. JustTrustMe and Xposed are theoretically able to bypass OkHTTP cert pinning, but they try to detect a specific `build().add(<CERT_FINGER_PRINT>)` constructor. But Jump does not use this, they first instantiate the object and then add a list of certificates (they have two fingerprints in their app), which JustTrustMe is not able to detect. I also tried [Frida](https://frida.re), but with the same result. Frida and all injection snippets I found did not detect the OkHTTP3 CertificatePinner correctly.

The next problem is, that Jump uses some sort of root and emulator detection. If you have a rooted phone or an Android emulator, the app seemingly stops working. As far as I understood, Xposed's hiding feature worked, but this required a lot of headaches to accomplish. A lastly, the Jump app seems to be obfuscated (I guess using ProGuard, but not sure about this). So, automagic tools like Xposed and alike often simply fail, because of obfuscation.

But as I stated in `Jump.md`, I really would appreciate it if somebody finds an easier way to sniff the HTTPS traffic. So far, this seems to be the only way for me.

Maybe I should add what I tried to `Jump.md`?. What do you think?

**Comment by adur1990** [comment]
Accidentally closed this PR, sorry.

**Comment by yoshimo** [comment]
It surprises me that Magisks Hide feature doesn't seem to successfully cloak the root-state for Jump.
Apart from the fact that they combat rooted phones, which confuses me even more. At least they should tell the user whats going on instead of looping forever.

**Comment by yoshimo** [comment]
Do you happen to know how they detect root as you went through parts of the code?

**Comment by ubahnverleih** [comment]
Oh, wow, thank you so much for the PR! And so much more for the guide!

**Pull request merged**
